name: CI

on:
  push:
    branches: [ "development", "main" ]
  pull_request:
    branches: [ "development", "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate --strict --working-dir=web/

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --working-dir=web/

      - name: Run test suite
        run: ./web/vendor/bin/phpunit -c tests/phpunit.xml
